include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - test/bin/widgets/widget_linted_1.dart
    - test/bin/widgets/widget_linted_2.dart
    - test/bin/widgets/widget_linted_3.dart
    - test/bin/widgets/widget_linted_final.dart

linter:
  rules:
    public_member_api_docs: false
    avoid_renaming_method_parameters: false
    flutter_style_todos: false
    always_use_package_imports: false
    avoid_relative_lib_imports: false
    prefer_asserts_with_message: false
    parameter_assignments: false
    unnecessary_library_directive: false
