name: sonnet_migrator
version: 0.1.0
description: Tool for migrating Flutter apps to use Sonnet
repository: https://github.com/Sonnet-International/sonnet

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  analyzer_plugin: ^0.11.2
  args: ^2.5.0
  collection: ^1.18.0
  meta: ^1.11.0
  sonnet: ^0.1.0
  sonnet_generator: ^0.1.0
  sonnet_linter: ^0.1.0
  source_gen: ^1.5.0
  string_literal_finder: ^1.3.0
  string_literal_finder_annotations: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter:
    sdk: flutter
  lints: ^3.0.0
  logging:
  test: ^1.24.0
  very_good_analysis:
