name: sonnet_migrator
version: 0.1.0
description: Tool for migrating Flutter apps to use Sonnet
repository: https://github.com/Sonnet-International/sonnet

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer:
  analyzer_plugin:
  args:
  collection:
  sonnet: ^0.1.0
  sonnet_linter: ^0.1.0
  source_gen:
  string_literal_finder:
  string_literal_finder_annotations:
  yaml:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis:
