name: sonnet_linter
version: 0.1.0
description: Lints Flutter apps for strings that could be internationalized using Sonnet
repository: https://github.com/Sonnet-International/sonnet

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  _fe_analyzer_shared: ^61.0.0
  analyzer: ^5.13.0
  analyzer_plugin: ^0.11.2
  collection: ^1.18.0
  custom_lint: ^0.6.0
  custom_lint_builder: ^0.6.1
  meta: ^1.11.0
  number_to_character: ^0.0.12
  path: ^1.9.0
  pubspec_parse: ^1.3.0
  sonnet: ^0.1.0
  sonnet_generator: ^0.1.0
  source_gen: ^1.5.0
  string_literal_finder: ^1.3.0
  string_literal_finder_annotations: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.0.0
  logging:
  mockito: ^5.0.0
  mocktail: ^0.3.0
  test: ^1.0.0
  very_good_analysis:
